// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Get application metadata such as version and author information. */
	metadata: () => __TAURI_INVOKE<MetadataConfig>("metadata"),
	options: () => __TAURI_INVOKE<OptionsConfig>("options"),
	setOptions: (options: OptionsConfig) => __TAURI_INVOKE<void>("set_options", { options }),
	/**  Get the list of available LLM providers. */
	providers: () => __TAURI_INVOKE<string[]>("providers"),
	/**  Get the current LLM provider. */
	currentProvider: () => __TAURI_INVOKE<string>("current_provider"),
	/** Switch the current LLM provider to the specified one. */
	switchProvider: (provider: string) => typedError<null, string>(__TAURI_INVOKE("switch_provider", { provider })),
	/**  Get the list of available models for the current LLM provider. */
	models: () => __TAURI_INVOKE<string[]>("models"),
	/**  Get the current model for the current LLM provider. */
	currentModel: () => __TAURI_INVOKE<string>("current_model"),
	/**  Switch the current model for the current LLM provider to the specified one. */
	switchModel: (model: string) => __TAURI_INVOKE<void>("switch_model", { model }),
	apiKey: () => __TAURI_INVOKE<string>("api_key"),
	/**  Set the API key for the current LLM provider. */
	setKey: (key: string) => __TAURI_INVOKE<void>("set_key", { key }),
	/**  Save configuration to file. */
	saveConfig: () => typedError<null, string>(__TAURI_INVOKE("save_config")),
	setZoom: (scale: number | null) => typedError<null, string>(__TAURI_INVOKE("set_zoom", { scale })),
	goBack: () => typedError<null, string>(__TAURI_INVOKE("go_back")),
	goForward: () => typedError<null, string>(__TAURI_INVOKE("go_forward")),
	/**  Close the application window with a fade-out animation. */
	close: () => __TAURI_INVOKE<void>("close"),
	/**  Minimize the application window. */
	minimize: () => __TAURI_INVOKE<void>("minimize"),
};

/* Types */
export type MetadataConfig = {
	author?: string,
	title?: string,
	version?: string,
	log_level?: string,
};

export type OptionsConfig = {
	persistSession?: boolean,
	muteWebview?: boolean,
	speedLock?: boolean,
	speedValue?: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

